export const GET_PERMISSION_ERROR = 'GET_PERMISSION_ERROR';
export const ASSIGN_LOCATION = 'ASSIGN_LOCATION';
export const SOURCE_INPUT_CHANGE = 'SOURCE_INPUT_CHANGE ';
export const DISTINATION_INPUT_CHANGE = 'DISTINATION_INPUT';
export const SEARCH_PLACE_SPINNER = 'SEARCH_PLACE_SPINNER';
export const SEARCH_PLACE_SUCCESS = 'SEARCH_PLACE_SUCCESS';
export const SEARCH_PLACE_FAILED = 'SEARCH_PLACE_FAILED';
export const GO_TO_CURRENT_LOCATION = 'GO_TO_CURRENT_LOCATION';
